version = 1

test_patterns = [
  "**/*.test.ts",
  "**/*.test.js",
  "**/*.spec.ts",
  "**/*.spec.js"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  style_guide = "standard"
  plugins = ["typescript"]

[[analyzers]]
name = "test-coverage"
enabled = true
